### ISSUE TITLE
Enable Wiki

### ISSUE THREAD

**Issue by tajmone** [curiousdannii/hugo#4]
Hi Dannii,

could you please enable the repository Wiki for public contributions. I'd like to add a couple of link to Hugo related assets, and it would useful if users could add also useful notes about building Hugo on various platforms — or any Hugo related information, really, for there aren't many places to discuss Hugo right now; and this repository is certainly a pivotal reference for Hugo development.

Thanks.

**Comment by curiousdannii** [comment]
It might be better to do this at https://bitbucket.org/0branch/hugo-unix/ - It's now being maintained by people who actually know the Hugo source code. (Though the glk code isn't actually present in that repository currently.) I was thinking of changing this to be a fork of that instead.

@realnc What do you think?

**Comment by tajmone** [comment]
I've visited that repository (following links in your issues), but overall I prefer GitHub when it comes to tools like Wikis, Dashboard, etc., for it has more features. I have a Bitbucket account, and some repositories there, but my impression is that GitHub is more lively and tends to promote more interaction between projects.

I'm quite interested in the Glk side of Hugo, for I'd like to target Windows builds for experimentation.

> I was thinking of changing this to be a fork of that instead.

Indeed it would be a good thing if the two projects could be merged in a way that nothing is lost, bu that might require some extra work to integrate the two projects. 

Overall, Having a single project for Hugo makes more sense.

**Comment by realnc** [comment]
The bitbucket repo is owned by @0branch, so I'm pinging him here. Oh, hi Marc :-) The hugo-unix repo really was just this:

http://www.ifarchive.org/if-archive/programming/hugo/source/hugov31_unix_source.tar.gz

Which is why initially there was nothing in there other than what's in that tarball. With Hugo in general being a dead project upstream, there's no "official" Hugo repo. The real official repo at:

http://develop.generalcoffee.com/hugo/trac/browser/trunk

is unmaintained and nobody has access. And it's SVN, so really nobody would actually *want* access :-) So making this one the official one sounds good to me. Although it should really have just one branch (master), really, which should use the base code sources from the bitbucket repo.

The Hugor branch can be deleted, since there's nothing of use there. All relevant base code changes were merged into the bitbucket repo. The rest are just Hugor-specific changes that are of no interest.

As for the other branches, not sure what do about them. I don't even know if they even belong here. Just like the Hugor branch, they are part of third-party interpreters. Any changes they made to the base code are either specific to them, or should be submitted for merging into master.

In any event, the dead upstream ports (wxwidgets, Mac classic, Acorn, BeOS, MS-DOS, etc) can be ignored. The only one still relevant is the Unix port. So this repo should only have the base code, and the Unix stuff. Unless we want to also treat the Unix port as a third-party terp, in which case this repo should only have the base code (which means just the `sources` directory and readmes/license.) Every Hugo interpreter would then use this repo as the upstream Hugo base code.

The people I know of who maintain Hugo interpreters are @juhana (HugoJS), @bcressey (Gargoyle) and myself. I assume the emglk stuff is Juhana's?

What do you think?

**Comment by 0branch** [comment]
Hey! I've enabled the Wiki on Bitbucket—

> Anyone can view the wiki. Only those with repository write access can edit the wiki.

@realnc, please feel free to change those settings (or grant write access to others).

Best,
Marc
